# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: mailto.unmani@gmail.com
author_name: unmani-shinde
cloud_provider: vercel
contract_name: trust_contract
deployment_language: python
preset_name: production
project_name: ALGOTrust

