# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.7
_src_path: gh:algorandfoundation/algokit-beaker-default-template
author_email: mailto.unmani@gmail.com
author_name: unmani-shinde
contract_name: trust_contract
deployment_language: python
preset_name: production
project_name: ALGOTrust-contracts

